// <auto-generated />
using Consulting.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Consulting.Infrastructure.Migrations
{
    [DbContext(typeof(ConsultingContext))]
    partial class ConsultingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Consulting.Core.Models.Consultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Consultants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Experience = "Junior",
                            Firstname = "Jawad",
                            Lastname = "Chemlal"
                        },
                        new
                        {
                            Id = 2,
                            Experience = "Medior",
                            Firstname = "Xavier",
                            Lastname = "Piekara"
                        },
                        new
                        {
                            Id = 3,
                            Experience = "Senior",
                            Firstname = "Loic",
                            Lastname = "Ramelot"
                        });
                });

            modelBuilder.Entity("Consulting.Core.Models.ConsultantMission", b =>
                {
                    b.Property<int>("ConsultantId")
                        .HasColumnType("int");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("ConsultantId", "MissionId");

                    b.HasIndex("MissionId");

                    b.ToTable("ConsultantMissions");

                    b.HasData(
                        new
                        {
                            ConsultantId = 1,
                            MissionId = 3,
                            isActive = true
                        },
                        new
                        {
                            ConsultantId = 2,
                            MissionId = 1,
                            isActive = true
                        },
                        new
                        {
                            ConsultantId = 2,
                            MissionId = 3,
                            isActive = false
                        },
                        new
                        {
                            ConsultantId = 3,
                            MissionId = 2,
                            isActive = true
                        },
                        new
                        {
                            ConsultantId = 3,
                            MissionId = 3,
                            isActive = false
                        },
                        new
                        {
                            ConsultantId = 3,
                            MissionId = 1,
                            isActive = false
                        });
                });

            modelBuilder.Entity("Consulting.Core.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExperienceRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExperienceRequired = "Medior",
                            MaximumRate = 500,
                            Name = "Google"
                        },
                        new
                        {
                            Id = 2,
                            ExperienceRequired = "Senior",
                            MaximumRate = 700,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 3,
                            ExperienceRequired = "Junior",
                            MaximumRate = 400,
                            Name = "NRB"
                        });
                });

            modelBuilder.Entity("Consulting.Core.Models.ConsultantMission", b =>
                {
                    b.HasOne("Consulting.Core.Models.Consultant", "Consultant")
                        .WithMany("ConsultantMissions")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consulting.Core.Models.Mission", "Mission")
                        .WithMany("ConsultantMissions")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
